version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12

jobs:
  deploy:
    executor: node
    steps:
      - checkout
      - run:
          name: Pack library
          command: |
            jq '.version="'$CIRCLE_TAG'"' package.json > package.tmp && mv package.tmp package.json
            npm pack
      - run:
          name: Deploy library
          command: |
            curl -s -o output.msg -w '%{http_code}' -F package=@$(ls *.tgz) https://${GEMFURY_TOKEN}@push.fury.io/enovacom/ > output.code
            cat output.msg && test $(cat output.code) -eq 200

workflows:
  package-deploy:
    jobs:
      - deploy:
          context: gemfury-creds
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+){2}(-.*)?/
